//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admp.config {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    public sealed partial class Query : global::System.Configuration.ApplicationSettingsBase {
        
        private static Query defaultInstance = ((Query)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Query())));
        
        public static Query Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT TABLE_NAME FROM stroy.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE=\'BASE TAB" +
            "LE\'\r\n")]
        public string DboSelection {
            get {
                return ((string)(this["DboSelection"]));
            }
            set {
                this["DboSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [Users]")]
        public string UsersSelection {
            get {
                return ((string)(this["UsersSelection"]));
            }
            set {
                this["UsersSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [Types]")]
        public string UsersTypeSelection {
            get {
                return ((string)(this["UsersTypeSelection"]));
            }
            set {
                this["UsersTypeSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [Messages]")]
        public string MessagesSelection {
            get {
                return ((string)(this["MessagesSelection"]));
            }
            set {
                this["MessagesSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [Documents]")]
        public string DocumentsSelection {
            get {
                return ((string)(this["DocumentsSelection"]));
            }
            set {
                this["DocumentsSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT [USERS] (ID, NAME, SNAME, LOGIN, PASS, EMAIL) VALUES")]
        public string UserInsert {
            get {
                return ((string)(this["UserInsert"]));
            }
            set {
                this["UserInsert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT [TYPES] (ID, CONTENT, DESCRIPTION) VALUES")]
        public string UserTypeInsert {
            get {
                return ((string)(this["UserTypeInsert"]));
            }
            set {
                this["UserTypeInsert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT [DOCUMENTS] () VALUES")]
        public string DocumentInsert {
            get {
                return ((string)(this["DocumentInsert"]));
            }
            set {
                this["DocumentInsert"] = value;
            }
        }
    }
}
