//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admp.config {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    public sealed partial class Query : global::System.Configuration.ApplicationSettingsBase {
        
        private static Query defaultInstance = ((Query)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Query())));
        
        public static Query Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT TABLE_NAME FROM stroy.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE=\'BASE TAB" +
            "LE\'\r\n")]
        public string DboSelection {
            get {
                return ((string)(this["DboSelection"]));
            }
            set {
                this["DboSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("users")]
        public string UsersObject {
            get {
                return ((string)(this["UsersObject"]));
            }
            set {
                this["UsersObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("types")]
        public string UserTypesObject {
            get {
                return ((string)(this["UserTypesObject"]));
            }
            set {
                this["UserTypesObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("documents")]
        public string DocumentsObject {
            get {
                return ((string)(this["DocumentsObject"]));
            }
            set {
                this["DocumentsObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("messages")]
        public string MessagesObject {
            get {
                return ((string)(this["MessagesObject"]));
            }
            set {
                this["MessagesObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("message_types")]
        public string MessagesTypesObject {
            get {
                return ((string)(this["MessagesTypesObject"]));
            }
            set {
                this["MessagesTypesObject"] = value;
            }
        }
    }
}
